const getDOMSelectors = ({
  ALL_CARS_LIST_DOM_SELECTOR,
  CAR_TITLE_DOM_SELECTOR_QUERY_FROM_CAR,
  CAR_PRICE_DOM_SELECTOR_QUERY_FROM_CAR,
  CAR_DESCRIPTION_DOM_SELECTOR_QUERY_FROM_CAR,
  CAR_ANNOUNCMENT_DOM_SELECTOR_FROM_CAR,
  CAR_IMAGE_URL_DOM_SELECTOR_QUERY_FROM_CAR,
}) => ({
  ALL_CARS_LIST_DOM_SELECTOR,
  CAR_TITLE_DOM_SELECTOR_QUERY_FROM_CAR,
  CAR_PRICE_DOM_SELECTOR_QUERY_FROM_CAR,
  CAR_DESCRIPTION_DOM_SELECTOR_QUERY_FROM_CAR,
  CAR_ANNOUNCMENT_DOM_SELECTOR_FROM_CAR,
  CAR_IMAGE_URL_DOM_SELECTOR_QUERY_FROM_CAR,
});

module.exports = { getDOMSelectors };
