const LISTADO_COCHES_CONTENEDOR_DOM_SELECTOR = "div.container-fluid.listado";
const ALL_ANUNCIOS_COCHE_FROM_CONTENEDOR_DOM_SELECTOR = `${LISTADO_COCHES_CONTENEDOR_DOM_SELECTOR}  article.anuncio`;
const TITULO_COCHE_DOM_SELECTOR = "div.contenido-anuncio h2";
const PRECIO_COCHE_DOM_SELECTOR = "p.precio > span";
const DETAILS_COCHE_DOMSELECTOR = "div.contenido-anuncio ul";

export const AutoocasionConstConfig = {
  ALL_ANUNCIOS_COCHE_FROM_CONTENEDOR_DOM_SELECTOR,
  TITULO_COCHE_DOM_SELECTOR,
  PRECIO_COCHE_DOM_SELECTOR,
  DETAILS_COCHE_DOMSELECTOR,
};
